overrides:
  vite: npm:rolldown-vite@7.1.14
catalog:
  '@antfu/ni': ^27.0.1
  '@iconify-json/carbon': ^1.2.14
  '@leafer-in/animate': ^1.9.12
  '@types/node': ^22.18.13
  '@vitejs/plugin-vue': ^6.0.1
  '@vue/runtime-core': ^3.5.22
  '@vueuse/core': ^14.0.0
  '@xiaohe01/eslint-config': ^3.1.0
  '@xiaohe01/stylelint-config': ^2.4.0
  '@xiaohe01/tsconfig': ^2.0.0
  await-to-js: ^3.0.0
  es-toolkit: ^1.41.0
  eslint: ^9.38.0
  esno: ^4.8.0
  leafer-ui: ^1.9.12
  leafer-vue: ^3.1.1
  lint-staged: ^16.2.6
  ress: ^5.0.2
  simple-git-hooks: ^2.13.1
  stylelint: ^16.25.0
  typescript: ~5.8.3
  unocss: ^66.5.4
  unplugin-auto-import: ^20.2.0
  unplugin-vue-components: ^30.0.0
  vite: npm:rolldown-vite@7.1.14
  vue: ^3.5.22
  vue-tsc: ^3.1.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks